# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anaconda3=/usr/loca

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.randint(0, 10, size=(2,3,5))


### 4. Print a.


In [4]:
print(a)

[[[6 6 3 9 8]
  [1 8 2 6 1]
  [1 2 1 8 1]]

 [[2 8 1 4 1]
  [0 0 5 7 0]
  [8 2 0 8 6]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
b = np.ones((5,2,3))


### 6. Print b.


In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
def checkSizes(a: np.dtype, b: np.dtype):
    if a.ndim == b.ndim:
        return True
    else:
        return False

print(checkSizes(a, b))

True



### 8. Are you able to add a and b? Why or why not?


We can't because both matrices do not have the same shape (a has 2,3,5 and b has 5,2,3)



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [8]:
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [9]:
d = a + c
print(d)

[[[ 7.  7.  4. 10.  9.]
  [ 2.  9.  3.  7.  2.]
  [ 2.  3.  2.  9.  2.]]

 [[ 3.  9.  2.  5.  2.]
  [ 1.  1.  6.  8.  1.]
  [ 9.  3.  1.  9.  7.]]]


Now it works because both matrices have the same shape (2,3,5)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [10]:
print(a)
print(d)


[[[6 6 3 9 8]
  [1 8 2 6 1]
  [1 2 1 8 1]]

 [[2 8 1 4 1]
  [0 0 5 7 0]
  [8 2 0 8 6]]]
[[[ 7.  7.  4. 10.  9.]
  [ 2.  9.  3.  7.  2.]
  [ 2.  3.  2.  9.  2.]]

 [[ 3.  9.  2.  5.  2.]
  [ 1.  1.  6.  8.  1.]
  [ 9.  3.  1.  9.  7.]]]


The difference comes from the fact that a is a matrix of random integers, while d is the result of adding a + c


### 12. Multiply a and c. Assign the result to e.


In [11]:
e = a * c
print(e)

[[[6. 6. 3. 9. 8.]
  [1. 8. 2. 6. 1.]
  [1. 2. 1. 8. 1.]]

 [[2. 8. 1. 4. 1.]
  [0. 0. 5. 7. 0.]
  [8. 2. 0. 8. 6.]]]




### 13. Does e equal to a? Why or why not?


In [12]:
print(np.array_equal(a, e))

True


They are both equal because c is a matrix of 1s, so multiplying any number with 1 is gonna return the same number.



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [13]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"d_max is {d_max}, d_min is {d_min}, and d_mean is {d_mean}")

d_max is 10.0, d_min is 1.0, and d_mean is 4.833333333333333



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [14]:
f = np.empty((2, 3, 5))
print(f)

[[[6. 6. 3. 9. 8.]
  [1. 8. 2. 6. 1.]
  [1. 2. 1. 8. 1.]]

 [[2. 8. 1. 4. 1.]
  [0. 0. 5. 7. 0.]
  [8. 2. 0. 8. 6.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [15]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i][j][k]
            if val == d_min:
                f[i][j][k] = 0
            elif val == d_max:
                f[i][j][k] = 100
            elif val == d_mean:
                f[i][j][k] = 50
            elif d_min < val < d_mean:
                f[i][j][k] = 25
            elif d_mean < val < d_max:
                f[i][j][k] = 75
                
print(f)

[[[ 75.  75.  25. 100.  75.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  25.  25.  75.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [  0.   0.  75.  75.   0.]
  [ 75.  25.   0.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [16]:
print("Array d is\n", d)
print("Array f is \n", f)

Array d is
 [[[ 7.  7.  4. 10.  9.]
  [ 2.  9.  3.  7.  2.]
  [ 2.  3.  2.  9.  2.]]

 [[ 3.  9.  2.  5.  2.]
  [ 1.  1.  6.  8.  1.]
  [ 9.  3.  1.  9.  7.]]]
Array f is 
 [[[ 75.  75.  25. 100.  75.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  25.  25.  75.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [  0.   0.  75.  75.   0.]
  [ 75.  25.   0.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [41]:
f = np.array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])

print(f)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
